name: Build and Test
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Download LLVM-PSTL unit tests
      run: |
        cd test-llvm-pstl && ./bootstrap.sh
    - name: Build and run unit tests (Release)
      run: |
        mkdir build-release
        cd build-release
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j all pstld-build-llvm-tests
        make test
    - name: Build and run unit tests (Debug)
      run: |
        mkdir build-debug
        cd build-debug
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make -j all pstld-build-llvm-tests
        make test
    - name: Build and run unit tests (ASAN)
      run: |
        mkdir build-asan
        cd build-asan
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fno-omit-frame-pointer -fsanitize=address" ..
        make -j all pstld-build-llvm-tests
        make test
    - name: Build and run unit tests (UBSAN)
      run: |
        mkdir build-ubsan
        cd build-ubsan
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fno-omit-frame-pointer -fsanitize=undefined" ..
        make -j all pstld-build-llvm-tests
        make test
