name: Build and Test
on: [push, workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        xcode-version: [13.4.1, 14.1]
    runs-on: [macos-12]
    steps:
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app'
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Download LLVM and MSVC unit tests
      run: |
        cd test-llvm-pstl && ./bootstrap.sh && cd -
        cd test-msvc-stl && ./bootstrap.sh
    - name: Build and run unit tests (Debug)
      run: |
        mkdir build-debug
        cd build-debug
        cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug ..
        make -j all pstld-build-llvm-tests pstld-build-msvc-tests pstld-build-custom-tests
        make test
    - name: Build and run unit tests (Release)
      run: |
        mkdir build-release
        cd build-release
        cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..
        make -j all pstld-build-llvm-tests pstld-build-msvc-tests pstld-build-custom-tests
        make test
    - name: Build and run unit tests (ASAN)
      run: |
        mkdir build-asan
        cd build-asan
        cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fno-omit-frame-pointer -fsanitize=address" ..
        make -j all pstld-build-llvm-tests pstld-build-msvc-tests pstld-build-custom-tests
        make test
    - name: Build and run unit tests (UBSAN)
      run: |
        mkdir build-ubsan
        cd build-ubsan
        cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fno-omit-frame-pointer -fsanitize=undefined" ..
        make -j all pstld-build-llvm-tests pstld-build-msvc-tests pstld-build-custom-tests
        make test
